- name: install apache2
  hosts: all
  become: true
  tasks:
    - name: install httpd if os is redhat
      package:
       name: httpd
       state: latest
      when: ansible_os_family == "RedHat"
    - name: install apache2 if os is debian
      package: 
       name: apache2
       state: latest
      when: ansible_os_family == "Debian"

