- name: my 1st playbook
  hosts: all
  vars:
    animal: "tiger"  #global variable
  # vars_files:
  #   - ./var.txt
  vars_prompt:
    - name: animal
      prompt: Enther the animal name
      private: false
  tasks:
    - name: print animal
      debug:
        msg: "{{animal}}"
    - name: print animal2
      debug:
        msg: "{{animal}}"
    - name: print animal3
      debug:
        msg: "{{animal}}"
      vars:
        animal: "lion"
    - name: register value example
      shell: hostname
      register: myhostvalue
    - name: print hostname value from register
      debug:
        msg: "{{myhostvalue.stdout}}"